'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { sampleBundle } = require('./fixtures');
const {
  normalize, categoryRows, sourceLocation, editorDiagnostics, graphSlice, summaryText, isRelevantFile,
  isPathInside, entityRelationships, relatedEntities, relationshipTargets, entityFindings, neighborhoodIds,
  resolveEntityReferences
} = require('../src/model');

function model() { const b = sampleBundle(); return normalize(b.raw, { nodeConnections: b.nodeConnections, audit: b.audit, policy: b.policy }); }

test('normalizes graph and builds canonical entity indexes', () => { const m = model(); assert.equal(m.entityById.get('deployment:camera').kind, 'Deployment'); assert.equal(m.entitiesByCategory.get('topics')[0].name, '/robot/image_raw'); });
test('missing and duplicate graph IDs are made deterministic', () => { const b = sampleBundle(); b.raw.graph.nodes.push({ id: 'node:demo/CameraNode', kind: 'Node', name: 'Duplicate', package: 'demo' }, { kind: 'Topic', name: '/no-id' }); const a = normalize(b.raw), c = normalize(b.raw); assert.deepEqual(a.graph.nodes.map(n => n.id), c.graph.nodes.map(n => n.id)); assert.equal(new Set(a.graph.nodes.map(n => n.id)).size, a.graph.nodes.length); });
test('category counts preserve empty and populated categories', () => { const rows = categoryRows(model()); assert.equal(rows.find(x => x.key === 'deployments').count, 1); assert.ok(rows.some(x => x.key === 'auditFindings')); });
test('deployment resolves launch source location first', () => { const m = model(); const d = m.entityById.get('deployment:camera'); assert.deepEqual(sourceLocation('deployments', d.data, m), { file: '/ws/src/demo/launch/demo.launch.py', line: 1 }); });
test('malformed source line falls back safely to line one', () => { assert.deepEqual(sourceLocation('nodes', { file_path: '/x.py', line: 'bad' }, null), { file: '/x.py', line: 1 }); });
test('reconciles orphan static graph edges through nodes --show-connections', () => { const m = model(); assert.ok(m.orphanEdges.some(e => e.source === 'static')); const deployment = m.entityById.get('deployment:camera'); const pubs = relationshipTargets(m, deployment.id, 'publishes'); assert.equal(pubs[0].name, '/robot/image_raw'); });
test('incoming and outgoing indexes are consistent', () => { const m = model(); const rel = m.relationships.find(r => r.rel === 'deploys_as'); assert.ok(m.outgoing.get(rel.source).some(x => x.id === rel.id)); assert.ok(m.incoming.get(rel.target).some(x => x.id === rel.id)); });
test('equivalent relationships are deduplicated', () => { const m = model(); const keys = m.relationships.map(r => `${r.source}|${r.rel}|${r.target}`); assert.equal(new Set(keys).size, keys.length); });
test('source nodes and deployments keep relationship identity separate', () => { const m = model(); const source = [...m.entityById.values()].find(e => e.kind === 'Node' && e.name === 'camera_node'); const deployment = m.entityById.get('deployment:camera'); assert.notEqual(source.id, deployment.id); assert.ok(entityRelationships(m, source.id).some(r => r.target === deployment.id)); });
test('topic publisher grouping returns deployment actor', () => { const m = model(); const topic = [...m.entityById.values()].find(e => e.kind === 'Topic'); const publishers = relationshipTargets(m, topic.id, 'publishes', 'incoming'); assert.ok(publishers.some(e => e.kind === 'Deployment')); });
test('service provider and action server relationships are reconciled', () => { const m = model(); const service = [...m.entityById.values()].find(e => e.kind === 'Service'); const action = [...m.entityById.values()].find(e => e.kind === 'Action'); assert.equal(relationshipTargets(m, service.id, 'provides', 'incoming').length, 1); assert.equal(relationshipTargets(m, action.id, 'provides', 'incoming').length, 1); });
test('interface usage is linked from source endpoint evidence', () => { const m = model(); const iface = [...m.entityById.values()].find(e => e.kind === 'Interface' && e.data.name === 'Status'); assert.ok(relationshipTargets(m, iface.id, 'uses_interface', 'incoming').some(e => e.kind === 'Node')); });
test('audit findings associate to communication entities', () => { const m = model(); const topic = [...m.entityById.values()].find(e => e.kind === 'Topic'); assert.ok(entityFindings(m, topic.id).some(f => f.source === 'audit')); });
test('policy finding naming a source node does not spray to deployment', () => { const m = model(); const source = [...m.entityById.values()].find(e => e.kind === 'Node' && e.data.name === 'CameraNode'); const deployment = m.entityById.get('deployment:camera'); assert.ok(entityFindings(m, source.id).some(f => f.source === 'policy')); assert.equal(entityFindings(m, deployment.id).some(f => f.source === 'policy'), false); });
test('finding aliases resolve exact source node names first', () => { const m = model(); const ids = resolveEntityReferences(m, 'CameraNode'); assert.equal(ids.length, 1); assert.equal(m.entityById.get(ids[0]).kind, 'Node'); });
test('finding diagnostics are deduplicated and source-located', () => { const list = editorDiagnostics(model()); const keys = list.map(x => `${x.file}|${x.line}|${x.code}|${x.message}`); assert.equal(new Set(keys).size, keys.length); assert.ok(list.some(x => x.code === 'dynamic_ros_name')); });
test('related entity selector is deterministic', () => { const m = model(); const source = [...m.entityById.values()].find(e => e.kind === 'Node' && e.data.name === 'CameraNode'); const first = relatedEntities(m, source.id).map(e => e.id); const second = relatedEntities(m, source.id).map(e => e.id); assert.deepEqual(first, second); });
test('graph totals are for selected mode, not full graph', () => { const m = model(); const deps = graphSlice(m, 'deps', 350); const full = graphSlice(m, 'full', 350); assert.ok(deps.totalNodes < full.totalNodes); assert.ok(deps.nodes.every(n => n.kind === 'Package')); });
test('graph truncation is deterministic and edges reference displayed nodes only', () => { const b = sampleBundle(); b.raw.graph.nodes.push(...Array.from({ length: 40 }, (_, i) => ({ id: `node:extra/${i}`, kind: 'Node', name: `N${i}`, package: 'demo' }))); const m = normalize(b.raw); const a = graphSlice(m, 'full', 25), c = graphSlice(m, 'full', 25); assert.equal(a.truncated, true); assert.deepEqual(a.nodes.map(n => n.id), c.nodes.map(n => n.id)); const ids = new Set(a.nodes.map(n => n.id)); assert.ok(a.edges.every(e => ids.has(e.source) && ids.has(e.target))); });
test('graph maxNodes clamps invalid values', () => { const m = model(); assert.equal(graphSlice(m, 'full', -10).limit, 25); assert.equal(graphSlice(m, 'full', Number.NaN).limit, 350); assert.equal(graphSlice(m, 'full', 99999).limit, 2000); });
test('one and two hop neighborhoods expand correctly', () => { const input = { relationships: [{ source: 'a', target: 'b' }, { source: 'b', target: 'c' }, { source: 'c', target: 'd' }] }; assert.deepEqual([...neighborhoodIds(input, 'a', 1)].sort(), ['a', 'b']); assert.deepEqual([...neighborhoodIds(input, 'a', 2)].sort(), ['a', 'b', 'c']); });
test('graph filters include package/search/relationship and hide isolated', () => { const m = model(); const filtered = graphSlice(m, 'full', 350, { package: 'demo', search: 'camera', relationships: ['deploys_as'] }); assert.ok(filtered.nodes.every(n => JSON.stringify(n).toLowerCase().includes('camera'))); const hidden = graphSlice(m, 'comms', 350, { hideIsolated: true }); assert.ok(hidden.nodes.length <= graphSlice(m, 'comms', 350).nodes.length); });
test('summary includes audit and policy counts', () => assert.match(summaryText(model()), /Audit findings: 2[\s\S]*Policy violations: 1/));
test('relevant-file and workspace-scoped refresh helpers are conservative', () => { assert.equal(isRelevantFile('/ws/src/x.cpp'), true); assert.equal(isRelevantFile('/ws/photo.png'), false); assert.equal(isPathInside('/ws', '/ws/src/a.py'), true); assert.equal(isPathInside('/ws', '/tmp/a.py'), false); });
