'use strict';
const fs=require('node:fs'), path=require('node:path');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const ignoredTop=new Set(['.git','.github','.vscode','node_modules','test','fixtures','docs','demo','scripts']);
const ignoredFiles=new Set(['.DS_Store']);
function walk(dir,base=''){let out=[];for(const ent of fs.readdirSync(dir,{withFileTypes:true})){if(!base&&ignoredTop.has(ent.name))continue;if(ignoredFiles.has(ent.name)||ent.name.endsWith('.vsix'))continue;const rel=path.posix.join(base,ent.name),abs=path.join(dir,ent.name);if(ent.isDirectory())out=out.concat(walk(abs,rel));else out.push({name:`extension/${rel}`,data:fs.readFileSync(abs)})}return out}
function crc32(buf){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function dosDateTime(d=new Date()){let year=Math.max(1980,d.getFullYear());return {time:(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1),date:((year-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate()}}
function u16(n){const b=Buffer.alloc(2);b.writeUInt16LE(n);return b}function u32(n){const b=Buffer.alloc(4);b.writeUInt32LE(n>>>0);return b}
const manifest=`<?xml version="1.0" encoding="utf-8"?><PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011"><Metadata><Identity Language="en-US" Id="${pkg.name}" Version="${pkg.version}" Publisher="${pkg.publisher}"/><DisplayName>${pkg.displayName}</DisplayName><Description xml:space="preserve">${pkg.description}</Description><Tags>${(pkg.keywords||[]).join(',')}</Tags><Categories>${(pkg.categories||[]).join(',')}</Categories><GalleryFlags>Public</GalleryFlags><Properties><Property Id="Microsoft.VisualStudio.Code.Engine" Value="${pkg.engines.vscode}"/><Property Id="Microsoft.VisualStudio.Code.ExtensionKind" Value="workspace"/><Property Id="Microsoft.VisualStudio.Services.Links.Source" Value="${pkg.repository.url.replace(/\.git$/,'')}"/></Properties></Metadata><Installation><InstallationTarget Id="Microsoft.VisualStudio.Code"/></Installation><Dependencies/><Assets><Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true"/><Asset Type="Microsoft.VisualStudio.Services.Icons.Default" Path="extension/${pkg.icon}" Addressable="true"/><Asset Type="Microsoft.VisualStudio.Services.Content.Details" Path="extension/README.md" Addressable="true"/><Asset Type="Microsoft.VisualStudio.Services.Content.Changelog" Path="extension/CHANGELOG.md" Addressable="true"/><Asset Type="Microsoft.VisualStudio.Services.Content.License" Path="extension/LICENSE" Addressable="true"/></Assets></PackageManifest>`;
const contentTypes=`<?xml version="1.0" encoding="utf-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="json" ContentType="application/json"/><Default Extension="js" ContentType="application/javascript"/><Default Extension="md" ContentType="text/markdown"/><Default Extension="png" ContentType="image/png"/><Default Extension="svg" ContentType="image/svg+xml"/><Default Extension="txt" ContentType="text/plain"/><Default Extension="xml" ContentType="text/xml"/><Default Extension="" ContentType="application/octet-stream"/></Types>`;
const files=[{name:'extension.vsixmanifest',data:Buffer.from(manifest)},{name:'[Content_Types].xml',data:Buffer.from(contentTypes)},...walk('.')];
let offset=0,locals=[],centrals=[];const dt=dosDateTime();for(const f of files){const name=Buffer.from(f.name.replaceAll('\\','/')),data=f.data,crc=crc32(data);const local=Buffer.concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(dt.time),u16(dt.date),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);const central=Buffer.concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(dt.time),u16(dt.date),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]);centrals.push(central);offset+=local.length}
const centralBuf=Buffer.concat(centrals),localBuf=Buffer.concat(locals),end=Buffer.concat([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(centralBuf.length),u32(localBuf.length),u16(0)]);const out=`${pkg.name}-${pkg.version}.vsix`;fs.writeFileSync(out,Buffer.concat([localBuf,centralBuf,end]));console.log(`${out} (${fs.statSync(out).size} bytes, ${files.length} files)`);
